spring.application.name=budget-buddy

# 기본 활성화 프로필 설정 (local)
spring.profiles.active=local

# Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# Async Execution Configuration
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5
